<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121013121601 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql('ALTER TABLE pastes ADD COLUMN highlight BOOLEAN DEFAULT 1');
        
        $this->addSql('UPDATE pastes SET highlight = 1');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->addSql(
            'CREATE TABLE pastes__tmp (' .
                'id INTEGER PRIMARY KEY NOT NULL, ' .
                'timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, ' .
                'token VARCHAR(50), ' .
                'filename VARCHAR(100), ' .
                'ip BLOB(16), ' .
                'content_id INTEGER, ' .
                'FOREIGN KEY(content_id) REFERENCES paste_content(id)' .
            ')'
        );

        $this->addSql(
            'INSERT INTO pastes__tmp ' .
            'SELECT id, timestamp, token, filename, ip, content_id ' .
            'FROM pastes__tmp' 
        );

        $this->addSql('DROP TABLE pastes');

        $this->addSql('ALTER TABLE pastes__tmp RENAME TO pastes');
    }
}
