<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120820212710 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql('ALTER TABLE pastes ADD COLUMN ip BLOB(16)');
    }

    public function down(Schema $schema)
    {
        $this->addSql(
            'CREATE TEMPORARY TABLE pastes__tmp (' .
                'id INTEGER PRIMARY KEY NOT NULL, ' .
                'timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, ' .
                'paste TEXT NOT NULL, ' .
                'token VARCHAR(50) NOT NULL, ' .
                'filename VARCHAR(100)' .
            ')'
        );
        $this->addSql(
            'INSERT INTO pastes__tmp ' .
            'SELECT id, timestamp, paste, token, filename FROM pastes'
        );
        $this->addSql('DROP TABLE pastes');

        $this->addSql(
            'CREATE TABLE pastes (' .
                'id INTEGER PRIMARY KEY NOT NULL, ' .
                'timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, ' .
                'paste TEXT NOT NULL, ' .
                'token VARCHAR(50) NOT NULL, ' .
                'filename VARCHAR(100)' .
            ')'
        );
        $this->addSql(
            'INSERT INTO pastes ' .
            'SELECT id, timestamp, paste, token, filename FROM pastes__tmp'
        );
        $this->addSql('DROP TABLE pastes__tmp');
    }
}
