<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120929184739 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql(
            'CREATE TABLE paste_content (' .
                'id INTEGER PRIMARY KEY NOT NULL, ' .
                'content TEXT NOT NULL, ' .
                'digest CHAR(32)' .
            ')'
        );

        $this->addSql('ALTER TABLE pastes ADD COLUMN content_id INTEGER');

        $this->addSql(
            'INSERT INTO paste_content (content) ' .
            'SELECT paste ' .
            'FROM pastes ' . 
            'GROUP BY paste'
        );

        $this->addSql(
            'CREATE TABLE pastes__tmp (' .
                'id INTEGER PRIMARY KEY NOT NULL, ' .
                'timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, ' .
                'token VARCHAR(50), ' .
                'filename VARCHAR(100), ' .
                'ip BLOB(16), ' .
                'content_id INTEGER, ' .
                'FOREIGN KEY(content_id) REFERENCES paste_content(id)' .
            ')'
        );

        $this->addSql(
            'INSERT INTO pastes__tmp ' .
            'SELECT p.id, p.timestamp, p.token, p.filename, p.ip, c.id ' .
            'FROM pastes p, paste_content c ' .
            'WHERE c.content = p.paste' 
        );

        $this->addSql('DROP TABLE pastes');

        $this->addSql('ALTER TABLE pastes__tmp RENAME TO pastes');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->addSql(
            'CREATE TABLE pastes__tmp (' .
                'id INTEGER PRIMARY KEY NOT NULL, ' .
                'timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, ' .
                'paste TEXT NOT NULL, ' .
                'token VARCHAR(50), ' .
                'filename VARCHAR(100), ' .
                'ip BLOB(16) ' .
            ')'
        );

        $this->addSql(
            'INSERT INTO pastes__tmp ' .
            'SELECT p.id, p.timestamp, c.content, p.token, p.filename, p.ip ' .
            'FROM pastes p, paste_content c ' .
            'WHERE p.content_id = c.id'
        );

        $this->addSql('DROP TABLE pastes');

        $this->addSql('DROP TABLE paste_content');

        $this->addSql('ALTER TABLE pastes__tmp RENAME TO pastes');
    }
}
